apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worknomads-ingress
  namespace: worknomads
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "12m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.worknomads.example.com
      secretName: worknomads-tls
  rules:
    - host: api.worknomads.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80
