apiVersion: v1
kind: Service
metadata:
  name: submission-service
  namespace: worknomads
spec:
  selector:
    app: submission-service
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
